name: PiliPlus
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
# update when release
version: 2.0.4+1

environment:
  sdk: ">=3.10.0"
  flutter: 3.41.6 # update `.fvmrc` config

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  piliplus_native_ios26:
    path: packages/piliplus_native_ios26
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # dynamic color
  dynamic_color: ^1.8.1

  # get: ^4.7.2
  get:
    git:
      url: https://github.com/bggRGjQaUbCoE/getx.git
      ref: version_4.7.2

  # 缃戠粶
  dio: ^5.9.1
  cookie_jar: ^4.0.8
  connectivity_plus: ^7.0.0
  dio_http2_adapter: ^2.5.3

  # 鍥剧墖
  cached_network_image: ^3.4.1
  # extended_image: ^9.0.7
  saver_gallery: ^4.1.0

  # QRCode
  # qr_flutter: ^4.1.0
  pretty_qr_code: ^3.3.0

  # 瀛樺偍
  path_provider: ^2.1.5
  hive_ce: ^2.19.3

  # 璁惧淇℃伅
  device_info_plus: ^12.1.0
  # 鏉冮檺
  # permission_handler: ^12.0.0+1
  permission_handler_apple: ^9.4.7
  permission_handler_android: ^13.0.1
  permission_handler_platform_interface: ^4.3.0
  # 鍒嗕韩
  share_plus: ^12.0.0
  # cookie 绠＄悊
  # webview_cookie_manager: ^2.0.6
  # 娴忚鍣?  # webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5
  # 瑙ｅ喅sliver婊戝姩涓嶅悓姝?  # extended_nested_scroll_view: ^6.2.1
  extended_nested_scroll_view:
    git:
      url: https://github.com/bggRGjQaUbCoE/extended_nested_scroll_view.git
      ref: mod
  # 涓婃媺鍔犺浇
  # loading_more_list: ^7.1.0
  # 涓嬫媺鍒锋柊
  # pull_to_refresh_notification: ^3.1.0
  # 鍥炬爣
  font_awesome_flutter: 10.9.0
  # material_design_icons_flutter: ^7.0.7296
  material_design_icons_flutter:
    git:
      url: https://github.com/bggRGjQaUbCoE/material_design_icons_flutter.git
      ref: const
  # toast
  flutter_smart_dialog:
    git:
      url: https://github.com/bggRGjQaUbCoE/flutter_smart_dialog.git
      ref: main
  # 涓嬫粦鍏抽棴
  # dismissible_page: ^1.0.2
  # custom_sliding_segmented_control: ^1.8.4
  # 鍔犲瘑
  crypto: ^3.0.6
  encrypt: ^5.0.3

  # 瑙嗛鎾斁鍣?  media_kit: 1.1.11 # Primary package.
  # media_kit_video: ^1.2.5 # For video rendering.
  media_kit_video:
    git:
      url: https://github.com/bggRGjQaUbCoE/media-kit.git
      path: media_kit_video
      ref: version_1.2.5
  media_kit_libs_video: 1.0.5

  # 濯掍綋閫氱煡
  audio_service: ^0.18.15
  audio_session: ^0.2.2

  # 闊抽噺銆佷寒搴︺€佸睆骞曟帶鍒?  flutter_volume_controller: ^1.3.3
  wakelock_plus: ^1.2.8
  # universal_platform: ^1.1.0
  # auto_orientation:
  #   git:
  #     url: https://github.com/bggRGjQaUbCoE/auto_orientation.git
  #     ref: master
  native_device_orientation:
    git:
      url: https://github.com/bggRGjQaUbCoE/flutter_native_device_orientation.git
      ref: master
  protobuf: ^6.0.0
  # animations: ^2.0.11

  # 鑾峰彇appx淇℃伅
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.1
  # 闃叉姈鑺傛祦
  easy_debounce: ^2.0.3
  # refresh rate
  flutter_displaymode: ^0.7.0
  # scheme璺宠浆
  app_links: ^7.0.0
  # 寮瑰箷
  # ns_danmaku:
  #   git:
  #     url: https://github.com/bggRGjQaUbCoE/flutter_ns_danmaku.git
  #     ref: master
  canvas_danmaku:
    git:
      url: https://github.com/bggRGjQaUbCoE/canvas_danmaku.git
      ref: main
  # 鐘舵€佹爮鍥炬爣鎺у埗
  # status_bar_control: ^3.2.1
  # 浠ｇ悊
  # system_proxy: ^0.1.0
  # pip
  # floating: ^3.0.0
  floating:
    git:
      url: https://github.com/bggRGjQaUbCoE/floating.git
      ref: version-3
  # html瑙ｆ瀽
  html: ^0.15.4
  # html娓叉煋
  flutter_html: ^3.0.0-beta.2
  # 鏋侀獙
  gt3_flutter_plugin: ^0.1.0
  uuid: ^4.5.1
  # scrollable_positioned_list: ^0.3.8
  # nil: ^1.1.1
  catcher_2: ^2.1.0
  logger: ^2.5.0
  # waterfall layout
  waterfall_flow: ^3.1.1
  #璺戦┈鐏?  # marquee: ^2.3.0
  #瀵屾枃鏈?  # extended_text: ^14.1.0
  # chat_bottom_container: ^0.2.0
  chat_bottom_container:
    git:
      url: https://github.com/bggRGjQaUbCoE/flutter_chat_packages.git
      ref: main
      path: packages/chat_bottom_container
  image_picker: ^1.1.2
  intl: ^0.20.2
  archive: ^4.0.0
  flutter_svg: ^2.0.14
  image_cropper: ^12.0.0
  #瑙ｅ帇鐩存挱娑堟伅
  brotli: ^0.6.0
  expandable: ^5.0.1
  flex_seed_scheme: ^4.0.1
  live_photo_maker: ^0.0.6
  fl_chart: ^1.0.0
  synchronized: ^3.3.0
  # document_file_save_plus: ^2.0.0
  # webdav_client: ^1.2.2
  webdav_client:
    git:
      url: https://github.com/wgh136/webdav_client.git
      ref: main
  re_highlight: ^0.0.3
  flutter_sortable_wrap:
    git:
      url: https://github.com/bggRGjQaUbCoE/flutter_sortable_wrap.git
      ref: master
  web_socket_channel: ^3.0.3
  # image: ^4.7.1
  # window_manager: ^0.5.1
  window_manager:
    git:
      url: https://github.com/bggRGjQaUbCoE/window_manager.git
      path: packages/window_manager
      ref: main
  tray_manager: ^0.5.1
  # file_picker: ^10.3.3
  file_picker:
    git:
      url: https://github.com/bggRGjQaUbCoE/flutter_file_picker.git
      ref: mod
  super_sliver_list:
    git:
      url: https://github.com/bggRGjQaUbCoE/super_sliver_list.git
      ref: mod
  dlna_dart: ^0.1.0
  battery_plus: ^7.0.0
  material_new_shapes: ^1.0.0

  vector_math: any
  fixnum: any
  json_annotation: any
  stream_transform: any
  screen_brightness_platform_interface: any
  mime: any
  path: any
  collection: any
  material_color_utilities: any
  flutter_cache_manager: any
  http2: any
  screen_retriever: any
  characters: any

dependency_overrides:
  # screen_brightness: ^2.1.
  screen_brightness_ios: ^2.1.2
  screen_brightness_android: ^2.1.3
  screen_brightness_platform_interface: ^2.1.0
  path: ^1.9.1
  mime: ^2.0.0
  rxdart: ^0.28.0
  media_kit:
    git:
      url: https://github.com/My-Responsitories/media-kit.git
      path: media_kit
      ref: version_1.2.5
  media_kit_video:
    git:
      url: https://github.com/My-Responsitories/media-kit.git
      path: media_kit_video
      ref: version_1.2.5
  media_kit_libs_video:
    git:
      url: https://github.com/My-Responsitories/media-kit.git
      path: libs/universal/media_kit_libs_video
      ref: version_1.2.5
  media_kit_native_event_loop:
    git:
      url: https://github.com/My-Responsitories/media-kit.git
      path: media_kit_native_event_loop
      ref: version_1.2.5
  media_kit_libs_android_video:
    git:
      url: https://github.com/My-Responsitories/media-kit.git
      path: libs/android/media_kit_libs_android_video
      ref: version_1.2.5
  media_kit_libs_windows_video:
    git:
      url: https://github.com/My-Responsitories/media-kit.git
      path: libs/windows/media_kit_libs_windows_video
      ref: version_1.2.5
  media_kit_libs_ios_video:
    git:
      url: https://github.com/bggRGjQaUbCoE/media-kit.git
      path: libs/ios/media_kit_libs_ios_video
      ref: dev
  media_kit_libs_macos_video:
    git:
      url: https://github.com/bggRGjQaUbCoE/media-kit.git
      path: libs/macos/media_kit_libs_macos_video
      ref: dev
  font_awesome_flutter: 10.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  # hive_generator: ^2.0.1
  build_runner: ^2.10.3
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/logo/logo_2.png
  image_path_android: assets/images/logo/logo_2.png
  image_path_ios: assets/images/logo/logo.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/logo/logo_2.png
  adaptive_icon_monochrome: assets/images/logo/logo_2.png
  macos:
    generate: true
    image_path: assets/images/logo/logo.png

flutter_native_splash:
  android_12:
    color: "#ffffff"
    color_dark: "#212121"
  color: "#ffffff"
  color_dark: "#212121"
  image: assets/images/logo/logo_2.png
  image_dark: assets/images/logo/logo_2.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - path: assets/images/
    - path: assets/images/lv/
    - path: assets/images/logo/
    - path: assets/images/logo/ico/
      platforms: [windows]
    - path: assets/images/logo/desktop/
      platforms: [linux, macos]
    - path: assets/images/live/
    - path: assets/images/video/
    - path: assets/images/paycoins/
    - path: assets/shaders/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: digital_id_num
      fonts:
        - asset: assets/fonts/digital_id_num.ttf
    - family: custom_icon
      fonts:
        - asset: assets/fonts/custom_icon.ttf
  #   - family: Jura-Bold
  #     fonts:
  #       - asset: assets/fonts/Jura-Bold.ttf
  # - family: HarmonyOS
  #   fonts:
  #     - asset: assets/fonts/HarmonyOS_Sans_SC_Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

